#!/usr/bin/env python
# Copyright (c) Paul Tagliamonte, 2012, under the terms and conditions of the
# COPYING file.

import json
import sys

from geoparse.point import Point
from geoparse.split import split_raw
from geoparse.defuzz import defuzz_feet

lastPoint = None
lines = json.load(open(sys.argv[1], 'r'))
dataset = [Point(line['lat'], line['lon'], line['time']) for line in
           sorted(lines, key=lambda(k): (k['time']))]

print len(dataset)
dataset = defuzz_feet(dataset, 300)  # FPS, btw.
print len(dataset)

for item in split_raw(dataset, 40):
    print item['data'][0].time
